# Auto-generated from proprietary-files.txt (downloaded blobs only)
PRODUCT_COPY_FILES += \
    device/xiaomi/spinel/vendor_blobs/proprietary/aosp-device-tree/rootdir/etc/fstab.mt6789:$(TARGET_COPY_OUT_RECOVERY)/root/first_stage_ramdisk/fstab.mt6789 \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/android.hardware.gatekeeper-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.gatekeeper-V1-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/android.hardware.gatekeeper@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.gatekeeper@1.0.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/android.hardware.keymaster@3.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.keymaster@3.0.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/android.hardware.keymaster@4.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.keymaster@4.0.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/android.hardware.keymaster@4.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.keymaster@4.1.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/android.hardware.security.keymint-V1-cpp.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.security.keymint-V1-cpp.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/android.hardware.security.keymint-V4-ndk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.security.keymint-V4-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/android.hardware.usb.gadget-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.usb.gadget-V1-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/android.hardware.usb.gadget@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.usb.gadget@1.0.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/lib_android_keymaster_keymint_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib_android_keymaster_keymint_utils.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/libgatekeeper_aidl.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgatekeeper_aidl.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/libkeymaster4_1support.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libkeymaster4_1support.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/libkeymaster4support.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libkeymaster4support.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/libkeymaster_messages.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libkeymaster_messages.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/libkeymaster_portable.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libkeymaster_portable.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/libkeymint.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libkeymint.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/libkeymint_support.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libkeymint_support.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/system/lib64/libpuresoftkeymasterdevice.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libpuresoftkeymasterdevice.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/bin/hw/android.hardware.boot-service.mtk:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.boot-service.mtk \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/bin/hw/android.hardware.gatekeeper-service.mitee:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper-service.mitee \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/bin/hw/android.hardware.security.keymint@4.0-service.mitee:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.security.keymint@4.0-service.mitee \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/bin/hw/android.hardware.usb-aidl-service.mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.usb-aidl-service.mediatek \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/bin/hw/android.hardware.usb.gadget-aidl-service.mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.usb.gadget-aidl-service.mediatek \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.mitee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.mitee.rc \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/init/android.hardware.security.keymint.mitee@4.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint.mitee@4.0-service.rc \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/init/android.hardware.usb-aidl-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb-aidl-service.mediatek.rc \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/init/android.hardware.usb.gadget-aidl-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb.gadget-aidl-service.mediatek.rc \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/init/hw/init.connectivity.common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.connectivity.common.rc \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/init/hw/init.connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.connectivity.rc \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/init/hw/init.mt6789.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mt6789.rc \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/init/hw/init.mt6789.usb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mt6789.usb.rc \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/init/hw/init.project.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.project.rc \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/permissions/android.hardware.usb.accessory.prebuilt.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.accessory.prebuilt.xml \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/permissions/android.hardware.usb.accessory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.accessory.xml \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/etc/permissions/android.hardware.usb.host.prebuilt.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.host.prebuilt.xml \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/android.hardware.gatekeeper-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.gatekeeper-V1-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/android.hardware.keymaster-V4-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.keymaster-V4-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/android.hardware.keymaster@3.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.keymaster@3.0.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/android.hardware.keymaster@4.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.keymaster@4.0.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/android.hardware.security.keymint-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.security.keymint-V1-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/android.hardware.security.keymint-V3-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.security.keymint-V3-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/android.hardware.security.keymint-V4-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.security.keymint-V4-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/android.hardware.usb-V3-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.usb-V3-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/android.hardware.usb.gadget-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.usb.gadget-V1-ndk.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/lib_android_keymaster_keymint_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib_android_keymaster_keymint_utils.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/libkeymaster4support.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymaster4support.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/libkeymaster_messages.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymaster_messages.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/libkeymaster_portable.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymaster_portable.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/libkeymint.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymint.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/libkeymint_remote_prov_support.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymint_remote_prov_support.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/libkeymint_support.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymint_support.so \
    device/xiaomi/spinel/vendor_blobs/proprietary/vendor/lib64/libpuresoftkeymasterdevice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpuresoftkeymasterdevice.so
